ui:
  frameDelay: 5000000
  theme: "DeFualt"

  artwork:
    blit: 'pixel'
    width: 1000
    height: 1000

  layout:
    # pages: [nowPlaying, queue, search]
    pages: [search, queue, nowPlaying]
    cols: 2
    rows: 2

settings:
  disableResize: false
  searchItemLimit: 10
  disableITermWorkaround: false

mappings:
  - key: SPACE
    modifiers:
    action: :playPauseToggle<CR>
  - key: c
    modifiers:
      - CTRL
    action: :quitApplication<CR>
